version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework:spring-test
    versions:
    - 5.3.3
    - 5.3.4
    - 5.3.5
  - dependency-name: org.springframework:spring-orm
    versions:
    - 5.3.3
    - 5.3.4
    - 5.3.5
  - dependency-name: org.springframework:spring-context
    versions:
    - 5.3.3
    - 5.3.4
    - 5.3.5
  - dependency-name: org.springframework:spring-aspects
    versions:
    - 5.3.3
    - 5.3.4
    - 5.3.5
  - dependency-name: org.springframework:spring-beans
    versions:
    - 5.3.3
    - 5.3.4
    - 5.3.5
  - dependency-name: org.springframework:spring-core
    versions:
    - 5.3.3
    - 5.3.4
    - 5.3.5
  - dependency-name: joda-time:joda-time
    versions:
    - 2.10.9
  - dependency-name: org.springframework.data:spring-data-jpa
    versions:
    - 2.1.8.RELEASE
